### ISSUE TITLE
dockernode.go issue while running `go install`

### ISSUE THREAD

**Issue by punalpatel** [whyrusleeping/iptb#44] opened 2018-03-12 17:22 UTC
While following steps in https://discuss.ipfs.io/t/testing-ipfs-with-iptb/1232:

go install                                                         ✓  ⚙  4450  10:20:46
# github.com/whyrusleeping/iptb/util
util/dockernode.go:193:10: cannot use int(dur.Nanoseconds() / 1000000) (type int) as type uint in field value

**Comment by magik6k** [comment] 2018-03-13 14:08
I'm getting the following when trying to compile with current master (with and without `gx-go rw`): 

```
# github.com/whyrusleeping/iptb/util
util/dockernode.go:200:10: cannot use uint(dur.Nanoseconds() / 1000000) (type uint) as type int in field value
util/dockernode.go:218:9: cannot use uint(dur.Nanoseconds() / 1000000) (type uint) as type int in field value
util/dockernode.go:237:12: cannot use uint(bw * 1000000) (type uint) as type int in field value
util/dockernode.go:256:13: cannot use uint8(ratio) (type uint8) as type int in field value
```

Might be related to recent changes in go-ctrlnet / https://github.com/whyrusleeping/iptb/pull/43

cc @dgrisham

**Comment by dgrisham** [comment] 2018-03-13 15:17
Yeah, this is related to the go-ctrlnet changes. Just pull the most recent
master of go-ctrlnet, that should fix this (I'm not sure whether gx-go is
meant to handle that for you, but this is an easy fix either way).

**Comment by magik6k** [comment] 2018-03-13 16:22
The problem is that there is outdated go-ctrlnet in package.json - https://github.com/whyrusleeping/iptb/blob/master/package.json#L36

**Comment by punalpatel** [comment] 2018-03-13 16:25
I have latest go-ctrlnet and I don't seen any changes in last 29 days. https://github.com/whyrusleeping/go-ctrlnet.

 Punal@Punals-MBP  ~/go/src/github.com/whyrusleeping/iptb   master ?  go get -u github.com/whyrusleeping/go-ctrlnet
[done] [install] go-ctrlnet                    xxxxxxxxx 0s
 Punal@Punals-MBP  ~/go/src/github.com/whyrusleeping/iptb   master ?  go install                                                         ✓  ⚙  4511  09:21:50
# github.com/whyrusleeping/iptb/util
util/dockernode.go:193:10: cannot use int(dur.Nanoseconds() / 1000000) (type int) as type uint in field value
 Punal@Punals-MBP  ~/go/src/github.com/whyrusleeping/iptb   master ? 

still seeing same issue.

**Comment by magik6k** [comment] 2018-03-13 16:34
Pushed a fix in https://github.com/whyrusleeping/iptb/pull/46

**Closed** 2018-03-13 16:40 UTC
